version: '2'

services:
    test:
        build: docker/php-cli
        image: matthiasnoback/building_autonomous_services_php_cli
        env_file: docker/.env
        user: ${HOST_UID}:${HOST_GID}
        volumes:
            - ./:/opt:cached
        network_mode: host
        command: "true" # do nothing when started by `docker-compose up`
