version: '2'

services:
    projector:
        extends:
            file: docker-compose.templates.yml
            service: php-cli
        command: php src/Common/projector.php
        networks:
            - default

    purchase_projector:
        extends:
            file: docker-compose.templates.yml
            service: php-cli
        command: php src/Purchase/projector.php

    sales_projector:
        extends:
            file: docker-compose.templates.yml
            service: php-cli
        command: php src/Sales/projector.php

    process_manager:
        extends:
            file: docker-compose.templates.yml
            service: php-cli
        command: php src/Common/process_manager.php
        networks:
            - default
