version: '2'

services:
    web:
        build: docker/nginx
        image: matthiasnoback/building_autonomous_services_nginx
        restart: on-failure
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.port=80"
        volumes:
            - ${PWD}:/opt:cached

    php-fpm:
        build: docker/php-fpm
        image: matthiasnoback/building_autonomous_services_php_fpm
        restart: on-failure
        env_file: docker/.env
        user: ${HOST_UID}:${HOST_GID}
        volumes:
            - ${PWD}:/opt:cached

    php-cli:
        build: docker/php-cli
        image: matthiasnoback/building_autonomous_services_php_cli
        restart: on-failure
        env_file: docker/.env
        user: ${HOST_UID}:${HOST_GID}
        volumes:
            - ${PWD}:/opt:cached
