version: '2'

services:
    ingress:
        image: traefik:1.7-alpine
        command: --docker
        ports:
            - "127.0.0.1:80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - traefik
            - default

    dashboard_web:
        build: docker/nginx
        image: matthiasnoback/building_autonomous_services_nginx
        restart: on-failure
        volumes:
            - ./:/opt:cached
        networks:
            - traefik
            - default
        depends_on:
            - dashboard_php
        environment:
            - SERVER_NAME=dashboard.localtest.me
            - PHP_BACKEND=dashboard_php
            - ROOT=/opt/src/Dashboard/public
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.port=80"
            - "traefik.backend=dashboard_web"
            - "traefik.frontend.rule=Host:dashboard.localtest.me"

    dashboard_php:
        build: docker/php-fpm
        image: matthiasnoback/building_autonomous_services_php_fpm
        restart: on-failure
        env_file: docker/.env
        user: ${HOST_UID}:${HOST_GID}
        volumes:
            - ./:/opt:cached
        networks:
            - default
        depends_on:
            - catalog_web
            - purchase_web
            - sales_web

    catalog_web:
        build: docker/nginx
        image: matthiasnoback/building_autonomous_services_nginx
        restart: on-failure
        volumes:
            - ./:/opt:cached
        networks:
            - traefik
            - default
        depends_on:
            - catalog_php
        environment:
            - SERVER_NAME=catalog.localtest.me
            - PHP_BACKEND=catalog_php
            - ROOT=/opt/src/Catalog/public
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.port=80"
            - "traefik.backend=catalog_web"
            - "traefik.frontend.rule=Host:catalog.localtest.me"

    catalog_php:
        build: docker/php-fpm
        image: matthiasnoback/building_autonomous_services_php_fpm
        restart: on-failure
        env_file: docker/.env
        user: ${HOST_UID}:${HOST_GID}
        networks:
            - default
        volumes:
            - ./:/opt:cached

    sales_web:
        build: docker/nginx
        image: matthiasnoback/building_autonomous_services_nginx
        restart: on-failure
        volumes:
            - ./:/opt:cached
        networks:
            - traefik
            - default
        depends_on:
            - sales_php
        environment:
            - SERVER_NAME=sales.localtest.me
            - PHP_BACKEND=sales_php
            - ROOT=/opt/src/Sales/public
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.port=80"
            - "traefik.backend=sales_web"
            - "traefik.frontend.rule=Host:sales.localtest.me"

    sales_php:
        build: docker/php-fpm
        image: matthiasnoback/building_autonomous_services_php_fpm
        restart: on-failure
        env_file: docker/.env
        user: ${HOST_UID}:${HOST_GID}
        volumes:
            - ./:/opt:cached
        networks:
            - default

    purchase_web:
        build: docker/nginx
        image: matthiasnoback/building_autonomous_services_nginx
        restart: on-failure
        volumes:
            - ./:/opt:cached
        networks:
            - traefik
            - default
        depends_on:
            - purchase_php
        environment:
            - SERVER_NAME=purchase.localtest.me
            - PHP_BACKEND=purchase_php
            - ROOT=/opt/src/Purchase/public
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.port=80"
            - "traefik.backend=purchase_web"
            - "traefik.frontend.rule=Host:purchase.localtest.me"

    purchase_php:
        build: docker/php-fpm
        image: matthiasnoback/building_autonomous_services_php_fpm
        restart: on-failure
        env_file: docker/.env
        user: ${HOST_UID}:${HOST_GID}
        volumes:
            - ./:/opt:cached
        networks:
            - default

    stock_web:
        build: docker/nginx
        image: matthiasnoback/building_autonomous_services_nginx
        restart: on-failure
        volumes:
            - ./:/opt:cached
        networks:
            - traefik
            - default
        depends_on:
            - stock_php
        environment:
            - SERVER_NAME=stock.localtest.me
            - PHP_BACKEND=stock_php
            - ROOT=/opt/src/Stock/public
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.port=80"
            - "traefik.backend=stock_web"
            - "traefik.frontend.rule=Host:stock.localtest.me"

    stock_php:
        build: docker/php-fpm
        image: matthiasnoback/building_autonomous_services_php_fpm
        restart: on-failure
        env_file: docker/.env
        user: ${HOST_UID}:${HOST_GID}
        volumes:
            - ./:/opt:cached
        networks:
            - default

networks:
    traefik: ~
